[package]
name = "isekaimaid-cache-microservice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_cbor = "0.11.2"
serde="1.0"
serde_derive = "1.0"
ciborium="0.2"
